spring.application.name=organization
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
documentation.application.description=${APP_DESCRIPTION:Organization microservice}
documentation.application.version=${APP_VERSION:0.0.1}

# OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
